/*

 PRESSSTART.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 1
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\gbtd_files\font.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define PressStartTextWidth 11
#define PressStartTextHeight 1
#define PressStartTextBank 0

#define PressStartText PressStartTextPLN0
const unsigned char PressStartTextPLN0[] =
{
  0x3F,0x41,0x34,0x42,0x42,0x4A,0x42,0x43,0x30,0x41,
  0x43
};

const unsigned char PressStartTextPLN1[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00
};

/* End of PRESSSTART.C */
