/*

 PRESSSTART.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 1
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\gbtd_files\font.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __pressstart_h_INCLUDE
#define __pressstart_h_INCLUDE

#define PressStartTextWidth 11
#define PressStartTextHeight 1
#define PressStartTextBank 0

#define PressStartText PressStartTextPLN0
extern const unsigned char PressStartTextPLN0[];
extern const unsigned char PressStartTextPLN1[];

#endif

/* End of PRESSSTART.H */
