/*

 MAP01.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 30
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map01_h_INCLUDE
#define __map01_h_INCLUDE

#define Map01Width 40
#define Map01Height 30
#define Map01Bank 0

#define Map01 Map01PLN0
extern const unsigned char Map01PLN0[];
extern const unsigned char Map01PLN1[];

#endif

/* End of MAP01.H */
