/*

 MAPZERO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 50 x 32
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mapzero_h_INCLUDE
#define __mapzero_h_INCLUDE

#define MapZeroWidth 50
#define MapZeroHeight 32
#define MapZeroBank 0

#define MapZero MapZeroPLN0
extern const unsigned char MapZeroPLN0[];
extern const unsigned char MapZeroPLN1[];

#endif

/* End of MAPZERO.H */
