/*

 PLAYERTILES6.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playertiles6_h_INCLUDE
#define __playertiles6_h_INCLUDE

/* Bank of tiles. */
#define PlayerTiles6Bank 0

/* Super Gameboy palette 0 */
#define PlayerTiles6SGBPal0c0 6076
#define PlayerTiles6SGBPal0c1 8935
#define PlayerTiles6SGBPal0c2 6596
#define PlayerTiles6SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerTiles6SGBPal1c0 6076
#define PlayerTiles6SGBPal1c1 8935
#define PlayerTiles6SGBPal1c2 6596
#define PlayerTiles6SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerTiles6SGBPal2c0 6076
#define PlayerTiles6SGBPal2c1 8935
#define PlayerTiles6SGBPal2c2 6596
#define PlayerTiles6SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerTiles6SGBPal3c0 6076
#define PlayerTiles6SGBPal3c1 8935
#define PlayerTiles6SGBPal3c2 6596
#define PlayerTiles6SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerTiles6CGBPal0c0 32767
#define PlayerTiles6CGBPal0c1 992
#define PlayerTiles6CGBPal0c2 744
#define PlayerTiles6CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define PlayerTiles6CGBPal1c0 6076
#define PlayerTiles6CGBPal1c1 8935
#define PlayerTiles6CGBPal1c2 6596
#define PlayerTiles6CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PlayerTiles6CGBPal2c0 6076
#define PlayerTiles6CGBPal2c1 8935
#define PlayerTiles6CGBPal2c2 6596
#define PlayerTiles6CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PlayerTiles6CGBPal3c0 6076
#define PlayerTiles6CGBPal3c1 8935
#define PlayerTiles6CGBPal3c2 6596
#define PlayerTiles6CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerTiles6CGBPal4c0 6076
#define PlayerTiles6CGBPal4c1 8935
#define PlayerTiles6CGBPal4c2 6596
#define PlayerTiles6CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerTiles6CGBPal5c0 6076
#define PlayerTiles6CGBPal5c1 8935
#define PlayerTiles6CGBPal5c2 6596
#define PlayerTiles6CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerTiles6CGBPal6c0 6076
#define PlayerTiles6CGBPal6c1 8935
#define PlayerTiles6CGBPal6c2 6596
#define PlayerTiles6CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerTiles6CGBPal7c0 6076
#define PlayerTiles6CGBPal7c1 8935
#define PlayerTiles6CGBPal7c2 6596
#define PlayerTiles6CGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char PlayerTiles6CGB[];
/* Start of tile array. */
extern const unsigned char PlayerTiles6[];

#endif

/* End of PLAYERTILES6.H */
