/*

 PLAYERTILES0.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playertiles0_h_INCLUDE
#define __playertiles0_h_INCLUDE

/* Bank of tiles. */
#define PlayerTiles0Bank 0

/* Super Gameboy palette 0 */
#define PlayerTiles0SGBPal0c0 6076
#define PlayerTiles0SGBPal0c1 8935
#define PlayerTiles0SGBPal0c2 6596
#define PlayerTiles0SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerTiles0SGBPal1c0 6076
#define PlayerTiles0SGBPal1c1 8935
#define PlayerTiles0SGBPal1c2 6596
#define PlayerTiles0SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerTiles0SGBPal2c0 6076
#define PlayerTiles0SGBPal2c1 8935
#define PlayerTiles0SGBPal2c2 6596
#define PlayerTiles0SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerTiles0SGBPal3c0 6076
#define PlayerTiles0SGBPal3c1 8935
#define PlayerTiles0SGBPal3c2 6596
#define PlayerTiles0SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerTiles0CGBPal0c0 32767
#define PlayerTiles0CGBPal0c1 992
#define PlayerTiles0CGBPal0c2 744
#define PlayerTiles0CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define PlayerTiles0CGBPal1c0 32767
#define PlayerTiles0CGBPal1c1 31
#define PlayerTiles0CGBPal1c2 20
#define PlayerTiles0CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PlayerTiles0CGBPal2c0 6076
#define PlayerTiles0CGBPal2c1 8935
#define PlayerTiles0CGBPal2c2 6596
#define PlayerTiles0CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PlayerTiles0CGBPal3c0 6076
#define PlayerTiles0CGBPal3c1 8935
#define PlayerTiles0CGBPal3c2 6596
#define PlayerTiles0CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerTiles0CGBPal4c0 6076
#define PlayerTiles0CGBPal4c1 8935
#define PlayerTiles0CGBPal4c2 6596
#define PlayerTiles0CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerTiles0CGBPal5c0 6076
#define PlayerTiles0CGBPal5c1 8935
#define PlayerTiles0CGBPal5c2 6596
#define PlayerTiles0CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerTiles0CGBPal6c0 6076
#define PlayerTiles0CGBPal6c1 8935
#define PlayerTiles0CGBPal6c2 6596
#define PlayerTiles0CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerTiles0CGBPal7c0 6076
#define PlayerTiles0CGBPal7c1 8935
#define PlayerTiles0CGBPal7c2 6596
#define PlayerTiles0CGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char PlayerTiles0CGB[];
/* Start of tile array. */
extern const unsigned char PlayerTiles0[];

#endif

/* End of PLAYERTILES0.H */
