/*

 PRIMARYBLOCKS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __primaryblocks_h_INCLUDE
#define __primaryblocks_h_INCLUDE

/* Bank of tiles. */
#define PrimaryBlocksBank 0

/* Super Gameboy palette 0 */
#define PrimaryBlocksSGBPal0c0 6076
#define PrimaryBlocksSGBPal0c1 8935
#define PrimaryBlocksSGBPal0c2 6596
#define PrimaryBlocksSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PrimaryBlocksSGBPal1c0 6076
#define PrimaryBlocksSGBPal1c1 8935
#define PrimaryBlocksSGBPal1c2 6596
#define PrimaryBlocksSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PrimaryBlocksSGBPal2c0 6076
#define PrimaryBlocksSGBPal2c1 8935
#define PrimaryBlocksSGBPal2c2 6596
#define PrimaryBlocksSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PrimaryBlocksSGBPal3c0 6076
#define PrimaryBlocksSGBPal3c1 8935
#define PrimaryBlocksSGBPal3c2 6596
#define PrimaryBlocksSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PrimaryBlocksCGBPal0c0 26431
#define PrimaryBlocksCGBPal0c1 30
#define PrimaryBlocksCGBPal0c2 25
#define PrimaryBlocksCGBPal0c3 0

/* Gameboy Color palette 1 */
#define PrimaryBlocksCGBPal1c0 26425
#define PrimaryBlocksCGBPal1c1 32290
#define PrimaryBlocksCGBPal1c2 25600
#define PrimaryBlocksCGBPal1c3 0

/* Gameboy Color palette 2 */
#define PrimaryBlocksCGBPal2c0 26425
#define PrimaryBlocksCGBPal2c1 467
#define PrimaryBlocksCGBPal2c2 10570
#define PrimaryBlocksCGBPal2c3 0

/* Gameboy Color palette 3 */
#define PrimaryBlocksCGBPal3c0 6076
#define PrimaryBlocksCGBPal3c1 8935
#define PrimaryBlocksCGBPal3c2 6596
#define PrimaryBlocksCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PrimaryBlocksCGBPal4c0 6076
#define PrimaryBlocksCGBPal4c1 8935
#define PrimaryBlocksCGBPal4c2 6596
#define PrimaryBlocksCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PrimaryBlocksCGBPal5c0 6076
#define PrimaryBlocksCGBPal5c1 8935
#define PrimaryBlocksCGBPal5c2 6596
#define PrimaryBlocksCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PrimaryBlocksCGBPal6c0 6076
#define PrimaryBlocksCGBPal6c1 8935
#define PrimaryBlocksCGBPal6c2 6596
#define PrimaryBlocksCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PrimaryBlocksCGBPal7c0 6076
#define PrimaryBlocksCGBPal7c1 8935
#define PrimaryBlocksCGBPal7c2 6596
#define PrimaryBlocksCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char PrimaryBlocksCGB[];
/* Start of tile array. */
extern const unsigned char PrimaryBlocks[];

#endif

/* End of PRIMARYBLOCKS.H */
