/*

 PRIMARYSWITCHBLOCKS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __primaryswitchblocks_h_INCLUDE
#define __primaryswitchblocks_h_INCLUDE

/* Bank of tiles. */
#define PrimarySwitchBlocksBank 0

/* Super Gameboy palette 0 */
#define PrimarySwitchBlocksSGBPal0c0 6076
#define PrimarySwitchBlocksSGBPal0c1 8935
#define PrimarySwitchBlocksSGBPal0c2 6596
#define PrimarySwitchBlocksSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PrimarySwitchBlocksSGBPal1c0 6076
#define PrimarySwitchBlocksSGBPal1c1 8935
#define PrimarySwitchBlocksSGBPal1c2 6596
#define PrimarySwitchBlocksSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PrimarySwitchBlocksSGBPal2c0 6076
#define PrimarySwitchBlocksSGBPal2c1 8935
#define PrimarySwitchBlocksSGBPal2c2 6596
#define PrimarySwitchBlocksSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PrimarySwitchBlocksSGBPal3c0 6076
#define PrimarySwitchBlocksSGBPal3c1 8935
#define PrimarySwitchBlocksSGBPal3c2 6596
#define PrimarySwitchBlocksSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PrimarySwitchBlocksCGBPal0c0 26431
#define PrimarySwitchBlocksCGBPal0c1 30
#define PrimarySwitchBlocksCGBPal0c2 25
#define PrimarySwitchBlocksCGBPal0c3 0

/* Gameboy Color palette 1 */
#define PrimarySwitchBlocksCGBPal1c0 26425
#define PrimarySwitchBlocksCGBPal1c1 32290
#define PrimarySwitchBlocksCGBPal1c2 25600
#define PrimarySwitchBlocksCGBPal1c3 0

/* Gameboy Color palette 2 */
#define PrimarySwitchBlocksCGBPal2c0 26425
#define PrimarySwitchBlocksCGBPal2c1 467
#define PrimarySwitchBlocksCGBPal2c2 10570
#define PrimarySwitchBlocksCGBPal2c3 0

/* Gameboy Color palette 3 */
#define PrimarySwitchBlocksCGBPal3c0 6076
#define PrimarySwitchBlocksCGBPal3c1 8935
#define PrimarySwitchBlocksCGBPal3c2 6596
#define PrimarySwitchBlocksCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PrimarySwitchBlocksCGBPal4c0 6076
#define PrimarySwitchBlocksCGBPal4c1 8935
#define PrimarySwitchBlocksCGBPal4c2 6596
#define PrimarySwitchBlocksCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PrimarySwitchBlocksCGBPal5c0 6076
#define PrimarySwitchBlocksCGBPal5c1 8935
#define PrimarySwitchBlocksCGBPal5c2 6596
#define PrimarySwitchBlocksCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PrimarySwitchBlocksCGBPal6c0 6076
#define PrimarySwitchBlocksCGBPal6c1 8935
#define PrimarySwitchBlocksCGBPal6c2 6596
#define PrimarySwitchBlocksCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PrimarySwitchBlocksCGBPal7c0 6076
#define PrimarySwitchBlocksCGBPal7c1 8935
#define PrimarySwitchBlocksCGBPal7c2 6596
#define PrimarySwitchBlocksCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char PrimarySwitchBlocksCGB[];
/* Start of tile array. */
extern const unsigned char PrimarySwitchBlocks[];

#endif

/* End of PRIMARYSWITCHBLOCKS.H */
