/*

 PROJECTILE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
const unsigned char ProjectileCGB[] =
{
  0x00
};
/* Start of tile array. */
const unsigned char Projectile[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x3C,0x3C,0x42,0x7E,0x81,0xFF,0x81,0xFF,
  0x81,0xFF,0x81,0xFF,0x42,0x7E,0x3C,0x3C
};

/* End of PROJECTILE.C */
