/*

 PROJECTILE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __projectile_h_INCLUDE
#define __projectile_h_INCLUDE

/* Bank of tiles. */
#define ProjectileBank 0

/* Super Gameboy palette 0 */
#define ProjectileSGBPal0c0 6076
#define ProjectileSGBPal0c1 8935
#define ProjectileSGBPal0c2 6596
#define ProjectileSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ProjectileSGBPal1c0 6076
#define ProjectileSGBPal1c1 8935
#define ProjectileSGBPal1c2 6596
#define ProjectileSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ProjectileSGBPal2c0 6076
#define ProjectileSGBPal2c1 8935
#define ProjectileSGBPal2c2 6596
#define ProjectileSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ProjectileSGBPal3c0 6076
#define ProjectileSGBPal3c1 8935
#define ProjectileSGBPal3c2 6596
#define ProjectileSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ProjectileCGBPal0c0 32767
#define ProjectileCGBPal0c1 744
#define ProjectileCGBPal0c2 6117
#define ProjectileCGBPal0c3 1379

/* Gameboy Color palette 1 */
#define ProjectileCGBPal1c0 6076
#define ProjectileCGBPal1c1 8935
#define ProjectileCGBPal1c2 6596
#define ProjectileCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define ProjectileCGBPal2c0 6076
#define ProjectileCGBPal2c1 8935
#define ProjectileCGBPal2c2 6596
#define ProjectileCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define ProjectileCGBPal3c0 6076
#define ProjectileCGBPal3c1 8935
#define ProjectileCGBPal3c2 6596
#define ProjectileCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define ProjectileCGBPal4c0 6076
#define ProjectileCGBPal4c1 8935
#define ProjectileCGBPal4c2 6596
#define ProjectileCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define ProjectileCGBPal5c0 6076
#define ProjectileCGBPal5c1 8935
#define ProjectileCGBPal5c2 6596
#define ProjectileCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define ProjectileCGBPal6c0 6076
#define ProjectileCGBPal6c1 8935
#define ProjectileCGBPal6c2 6596
#define ProjectileCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define ProjectileCGBPal7c0 6076
#define ProjectileCGBPal7c1 8935
#define ProjectileCGBPal7c2 6596
#define ProjectileCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char ProjectileCGB[];
/* Start of tile array. */
extern const unsigned char Projectile[];

#endif

/* End of PROJECTILE.H */
