/*

 SECONDARYSWITCHBLOCKS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __secondaryswitchblocks_h_INCLUDE
#define __secondaryswitchblocks_h_INCLUDE

/* Bank of tiles. */
#define SecondarSwitchBlocksBank 0

/* Super Gameboy palette 0 */
#define SecondarSwitchBlocksSGBPal0c0 6076
#define SecondarSwitchBlocksSGBPal0c1 8935
#define SecondarSwitchBlocksSGBPal0c2 6596
#define SecondarSwitchBlocksSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SecondarSwitchBlocksSGBPal1c0 6076
#define SecondarSwitchBlocksSGBPal1c1 8935
#define SecondarSwitchBlocksSGBPal1c2 6596
#define SecondarSwitchBlocksSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SecondarSwitchBlocksSGBPal2c0 6076
#define SecondarSwitchBlocksSGBPal2c1 8935
#define SecondarSwitchBlocksSGBPal2c2 6596
#define SecondarSwitchBlocksSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SecondarSwitchBlocksSGBPal3c0 6076
#define SecondarSwitchBlocksSGBPal3c1 8935
#define SecondarSwitchBlocksSGBPal3c2 6596
#define SecondarSwitchBlocksSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SecondarSwitchBlocksCGBPal0c0 26431
#define SecondarSwitchBlocksCGBPal0c1 30
#define SecondarSwitchBlocksCGBPal0c2 25
#define SecondarSwitchBlocksCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SecondarSwitchBlocksCGBPal1c0 26425
#define SecondarSwitchBlocksCGBPal1c1 32290
#define SecondarSwitchBlocksCGBPal1c2 25600
#define SecondarSwitchBlocksCGBPal1c3 0

/* Gameboy Color palette 2 */
#define SecondarSwitchBlocksCGBPal2c0 26425
#define SecondarSwitchBlocksCGBPal2c1 467
#define SecondarSwitchBlocksCGBPal2c2 10570
#define SecondarSwitchBlocksCGBPal2c3 0

/* Gameboy Color palette 3 */
#define SecondarSwitchBlocksCGBPal3c0 6076
#define SecondarSwitchBlocksCGBPal3c1 8935
#define SecondarSwitchBlocksCGBPal3c2 6596
#define SecondarSwitchBlocksCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define SecondarSwitchBlocksCGBPal4c0 6076
#define SecondarSwitchBlocksCGBPal4c1 8935
#define SecondarSwitchBlocksCGBPal4c2 6596
#define SecondarSwitchBlocksCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SecondarSwitchBlocksCGBPal5c0 6076
#define SecondarSwitchBlocksCGBPal5c1 8935
#define SecondarSwitchBlocksCGBPal5c2 6596
#define SecondarSwitchBlocksCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SecondarSwitchBlocksCGBPal6c0 6076
#define SecondarSwitchBlocksCGBPal6c1 8935
#define SecondarSwitchBlocksCGBPal6c2 6596
#define SecondarSwitchBlocksCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SecondarSwitchBlocksCGBPal7c0 6076
#define SecondarSwitchBlocksCGBPal7c1 8935
#define SecondarSwitchBlocksCGBPal7c2 6596
#define SecondarSwitchBlocksCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char SecondarSwitchBlocksCGB[];
/* Start of tile array. */
extern const unsigned char SecondarSwitchBlocks[];

#endif

/* End of SECONDARYSWITCHBLOCKS.H */
