/*

 SECONDARYBLOCKS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __secondaryblocks_h_INCLUDE
#define __secondaryblocks_h_INCLUDE

/* Bank of tiles. */
#define SecondaryBlocksBank 0

/* Super Gameboy palette 0 */
#define SecondaryBlocksSGBPal0c0 6076
#define SecondaryBlocksSGBPal0c1 8935
#define SecondaryBlocksSGBPal0c2 6596
#define SecondaryBlocksSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SecondaryBlocksSGBPal1c0 6076
#define SecondaryBlocksSGBPal1c1 8935
#define SecondaryBlocksSGBPal1c2 6596
#define SecondaryBlocksSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SecondaryBlocksSGBPal2c0 6076
#define SecondaryBlocksSGBPal2c1 8935
#define SecondaryBlocksSGBPal2c2 6596
#define SecondaryBlocksSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SecondaryBlocksSGBPal3c0 6076
#define SecondaryBlocksSGBPal3c1 8935
#define SecondaryBlocksSGBPal3c2 6596
#define SecondaryBlocksSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SecondaryBlocksCGBPal0c0 26431
#define SecondaryBlocksCGBPal0c1 30
#define SecondaryBlocksCGBPal0c2 25
#define SecondaryBlocksCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SecondaryBlocksCGBPal1c0 26425
#define SecondaryBlocksCGBPal1c1 32290
#define SecondaryBlocksCGBPal1c2 25600
#define SecondaryBlocksCGBPal1c3 0

/* Gameboy Color palette 2 */
#define SecondaryBlocksCGBPal2c0 26425
#define SecondaryBlocksCGBPal2c1 467
#define SecondaryBlocksCGBPal2c2 10570
#define SecondaryBlocksCGBPal2c3 0

/* Gameboy Color palette 3 */
#define SecondaryBlocksCGBPal3c0 6076
#define SecondaryBlocksCGBPal3c1 8935
#define SecondaryBlocksCGBPal3c2 6596
#define SecondaryBlocksCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define SecondaryBlocksCGBPal4c0 6076
#define SecondaryBlocksCGBPal4c1 8935
#define SecondaryBlocksCGBPal4c2 6596
#define SecondaryBlocksCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SecondaryBlocksCGBPal5c0 6076
#define SecondaryBlocksCGBPal5c1 8935
#define SecondaryBlocksCGBPal5c2 6596
#define SecondaryBlocksCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SecondaryBlocksCGBPal6c0 6076
#define SecondaryBlocksCGBPal6c1 8935
#define SecondaryBlocksCGBPal6c2 6596
#define SecondaryBlocksCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SecondaryBlocksCGBPal7c0 6076
#define SecondaryBlocksCGBPal7c1 8935
#define SecondaryBlocksCGBPal7c2 6596
#define SecondaryBlocksCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char SecondaryBlocksCGB[];
/* Start of tile array. */
extern const unsigned char SecondaryBlocks[];

#endif

/* End of SECONDARYBLOCKS.H */
