/*

 SPLASHDOWN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __splashdown_h_INCLUDE
#define __splashdown_h_INCLUDE

/* Bank of tiles. */
#define SplashdownBank 0

/* Super Gameboy palette 0 */
#define SplashdownSGBPal0c0 6076
#define SplashdownSGBPal0c1 8935
#define SplashdownSGBPal0c2 6596
#define SplashdownSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SplashdownSGBPal1c0 6076
#define SplashdownSGBPal1c1 8935
#define SplashdownSGBPal1c2 6596
#define SplashdownSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SplashdownSGBPal2c0 6076
#define SplashdownSGBPal2c1 8935
#define SplashdownSGBPal2c2 6596
#define SplashdownSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SplashdownSGBPal3c0 6076
#define SplashdownSGBPal3c1 8935
#define SplashdownSGBPal3c2 6596
#define SplashdownSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SplashdownCGBPal0c0 32767
#define SplashdownCGBPal0c1 21140
#define SplashdownCGBPal0c2 10570
#define SplashdownCGBPal0c3 5285

/* Gameboy Color palette 1 */
#define SplashdownCGBPal1c0 6076
#define SplashdownCGBPal1c1 8935
#define SplashdownCGBPal1c2 6596
#define SplashdownCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define SplashdownCGBPal2c0 6076
#define SplashdownCGBPal2c1 8935
#define SplashdownCGBPal2c2 6596
#define SplashdownCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define SplashdownCGBPal3c0 6076
#define SplashdownCGBPal3c1 8935
#define SplashdownCGBPal3c2 6596
#define SplashdownCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define SplashdownCGBPal4c0 6076
#define SplashdownCGBPal4c1 8935
#define SplashdownCGBPal4c2 6596
#define SplashdownCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SplashdownCGBPal5c0 6076
#define SplashdownCGBPal5c1 8935
#define SplashdownCGBPal5c2 6596
#define SplashdownCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SplashdownCGBPal6c0 6076
#define SplashdownCGBPal6c1 8935
#define SplashdownCGBPal6c2 6596
#define SplashdownCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SplashdownCGBPal7c0 6076
#define SplashdownCGBPal7c1 8935
#define SplashdownCGBPal7c2 6596
#define SplashdownCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char SplashdownCGB[];
/* Start of tile array. */
extern const unsigned char Splashdown[];

#endif

/* End of SPLASHDOWN.H */
