/*

 TIMETRAPSUP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __timetrapsup_h_INCLUDE
#define __timetrapsup_h_INCLUDE

/* Bank of tiles. */
#define TimeTrapsUpBank 0

/* Super Gameboy palette 0 */
#define TimeTrapsUpSGBPal0c0 6076
#define TimeTrapsUpSGBPal0c1 8935
#define TimeTrapsUpSGBPal0c2 6596
#define TimeTrapsUpSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TimeTrapsUpSGBPal1c0 6076
#define TimeTrapsUpSGBPal1c1 8935
#define TimeTrapsUpSGBPal1c2 6596
#define TimeTrapsUpSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TimeTrapsUpSGBPal2c0 6076
#define TimeTrapsUpSGBPal2c1 8935
#define TimeTrapsUpSGBPal2c2 6596
#define TimeTrapsUpSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TimeTrapsUpSGBPal3c0 6076
#define TimeTrapsUpSGBPal3c1 8935
#define TimeTrapsUpSGBPal3c2 6596
#define TimeTrapsUpSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TimeTrapsUpCGBPal0c0 26425
#define TimeTrapsUpCGBPal0c1 467
#define TimeTrapsUpCGBPal0c2 10570
#define TimeTrapsUpCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TimeTrapsUpCGBPal1c0 6076
#define TimeTrapsUpCGBPal1c1 8935
#define TimeTrapsUpCGBPal1c2 6596
#define TimeTrapsUpCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define TimeTrapsUpCGBPal2c0 6076
#define TimeTrapsUpCGBPal2c1 8935
#define TimeTrapsUpCGBPal2c2 6596
#define TimeTrapsUpCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TimeTrapsUpCGBPal3c0 6076
#define TimeTrapsUpCGBPal3c1 8935
#define TimeTrapsUpCGBPal3c2 6596
#define TimeTrapsUpCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TimeTrapsUpCGBPal4c0 6076
#define TimeTrapsUpCGBPal4c1 8935
#define TimeTrapsUpCGBPal4c2 6596
#define TimeTrapsUpCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TimeTrapsUpCGBPal5c0 6076
#define TimeTrapsUpCGBPal5c1 8935
#define TimeTrapsUpCGBPal5c2 6596
#define TimeTrapsUpCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TimeTrapsUpCGBPal6c0 6076
#define TimeTrapsUpCGBPal6c1 8935
#define TimeTrapsUpCGBPal6c2 6596
#define TimeTrapsUpCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TimeTrapsUpCGBPal7c0 6076
#define TimeTrapsUpCGBPal7c1 8935
#define TimeTrapsUpCGBPal7c2 6596
#define TimeTrapsUpCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char TimeTrapsUpCGB[];
/* Start of tile array. */
extern const unsigned char TimeTrapsUp[];

#endif

/* End of TIMETRAPSUP.H */
