/*

 TIMETRAPSDOWN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __timetrapsdown_h_INCLUDE
#define __timetrapsdown_h_INCLUDE

/* Bank of tiles. */
#define TimeTrapsDownBank 0

/* Super Gameboy palette 0 */
#define TimeTrapsDownSGBPal0c0 6076
#define TimeTrapsDownSGBPal0c1 8935
#define TimeTrapsDownSGBPal0c2 6596
#define TimeTrapsDownSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TimeTrapsDownSGBPal1c0 6076
#define TimeTrapsDownSGBPal1c1 8935
#define TimeTrapsDownSGBPal1c2 6596
#define TimeTrapsDownSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TimeTrapsDownSGBPal2c0 6076
#define TimeTrapsDownSGBPal2c1 8935
#define TimeTrapsDownSGBPal2c2 6596
#define TimeTrapsDownSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TimeTrapsDownSGBPal3c0 6076
#define TimeTrapsDownSGBPal3c1 8935
#define TimeTrapsDownSGBPal3c2 6596
#define TimeTrapsDownSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TimeTrapsDownCGBPal0c0 26425
#define TimeTrapsDownCGBPal0c1 467
#define TimeTrapsDownCGBPal0c2 10570
#define TimeTrapsDownCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TimeTrapsDownCGBPal1c0 6076
#define TimeTrapsDownCGBPal1c1 8935
#define TimeTrapsDownCGBPal1c2 6596
#define TimeTrapsDownCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define TimeTrapsDownCGBPal2c0 6076
#define TimeTrapsDownCGBPal2c1 8935
#define TimeTrapsDownCGBPal2c2 6596
#define TimeTrapsDownCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TimeTrapsDownCGBPal3c0 6076
#define TimeTrapsDownCGBPal3c1 8935
#define TimeTrapsDownCGBPal3c2 6596
#define TimeTrapsDownCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TimeTrapsDownCGBPal4c0 6076
#define TimeTrapsDownCGBPal4c1 8935
#define TimeTrapsDownCGBPal4c2 6596
#define TimeTrapsDownCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TimeTrapsDownCGBPal5c0 6076
#define TimeTrapsDownCGBPal5c1 8935
#define TimeTrapsDownCGBPal5c2 6596
#define TimeTrapsDownCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TimeTrapsDownCGBPal6c0 6076
#define TimeTrapsDownCGBPal6c1 8935
#define TimeTrapsDownCGBPal6c2 6596
#define TimeTrapsDownCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TimeTrapsDownCGBPal7c0 6076
#define TimeTrapsDownCGBPal7c1 8935
#define TimeTrapsDownCGBPal7c2 6596
#define TimeTrapsDownCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char TimeTrapsDownCGB[];
/* Start of tile array. */
extern const unsigned char TimeTrapsDown[];

#endif

/* End of TIMETRAPSDOWN.H */
