/*

 MAP16.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 20
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map16_h_INCLUDE
#define __map16_h_INCLUDE

#define Map16Width 40
#define Map16Height 20
#define Map16Bank 0

#define Map16 Map16PLN0
extern const unsigned char Map16PLN0[];
extern const unsigned char Map16PLN1[];

#endif

/* End of MAP16.H */
