/*

 MAP15.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 20
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map15_h_INCLUDE
#define __map15_h_INCLUDE

#define Map15Width 40
#define Map15Height 20
#define Map15Bank 0

#define Map15 Map15PLN0
extern const unsigned char Map15PLN0[];
extern const unsigned char Map15PLN1[];

#endif

/* End of MAP15.H */
