/*

 MAP18.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 28 x 22
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map18_h_INCLUDE
#define __map18_h_INCLUDE

#define Map18Width 28
#define Map18Height 22
#define Map18Bank 0

#define Map18 Map18PLN0
extern const unsigned char Map18PLN0[];
extern const unsigned char Map18PLN1[];

#endif

/* End of MAP18.H */
