/*

 MAP19.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 28 x 24
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map19_h_INCLUDE
#define __map19_h_INCLUDE

#define Map19Width 28
#define Map19Height 24
#define Map19Bank 0

#define Map19 Map19PLN0
extern const unsigned char Map19PLN0[];
extern const unsigned char Map19PLN1[];

#endif

/* End of MAP19.H */
