/*

 MAP14.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 30
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map14_h_INCLUDE
#define __map14_h_INCLUDE

#define Map14Width 20
#define Map14Height 30
#define Map14Bank 0

#define Map14 Map14PLN0
extern const unsigned char Map14PLN0[];
extern const unsigned char Map14PLN1[];

#endif

/* End of MAP14.H */
