/*

 TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 11

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tileset_h_INCLUDE
#define __tileset_h_INCLUDE

/* Bank of tiles. */
#define TilesetBank 0

/* Super Gameboy palette 0 */
#define TilesetSGBPal0c0 6076
#define TilesetSGBPal0c1 8935
#define TilesetSGBPal0c2 6596
#define TilesetSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TilesetSGBPal1c0 6076
#define TilesetSGBPal1c1 8935
#define TilesetSGBPal1c2 6596
#define TilesetSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TilesetSGBPal2c0 6076
#define TilesetSGBPal2c1 8935
#define TilesetSGBPal2c2 6596
#define TilesetSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TilesetSGBPal3c0 6076
#define TilesetSGBPal3c1 8935
#define TilesetSGBPal3c2 6596
#define TilesetSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TilesetCGBPal0c0 26425
#define TilesetCGBPal0c1 8935
#define TilesetCGBPal0c2 6596
#define TilesetCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TilesetCGBPal1c0 26425
#define TilesetCGBPal1c1 32290
#define TilesetCGBPal1c2 25600
#define TilesetCGBPal1c3 0

/* Gameboy Color palette 2 */
#define TilesetCGBPal2c0 26431
#define TilesetCGBPal2c1 30
#define TilesetCGBPal2c2 25
#define TilesetCGBPal2c3 0

/* Gameboy Color palette 3 */
#define TilesetCGBPal3c0 26425
#define TilesetCGBPal3c1 32290
#define TilesetCGBPal3c2 25600
#define TilesetCGBPal3c3 0

/* Gameboy Color palette 4 */
#define TilesetCGBPal4c0 26425
#define TilesetCGBPal4c1 467
#define TilesetCGBPal4c2 10570
#define TilesetCGBPal4c3 0

/* Gameboy Color palette 5 */
#define TilesetCGBPal5c0 6076
#define TilesetCGBPal5c1 8935
#define TilesetCGBPal5c2 6596
#define TilesetCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TilesetCGBPal6c0 6076
#define TilesetCGBPal6c1 8935
#define TilesetCGBPal6c2 6596
#define TilesetCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TilesetCGBPal7c0 6076
#define TilesetCGBPal7c1 8935
#define TilesetCGBPal7c2 6596
#define TilesetCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char TilesetCGB[];
/* Start of tile array. */
extern const unsigned char Tileset[];

#endif

/* End of TILESET.H */
