/*

 TILESET1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tileset1_h_INCLUDE
#define __tileset1_h_INCLUDE

/* Bank of tiles. */
#define Tileset1Bank 0

/* Super Gameboy palette 0 */
#define Tileset1SGBPal0c0 6076
#define Tileset1SGBPal0c1 8935
#define Tileset1SGBPal0c2 6596
#define Tileset1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Tileset1SGBPal1c0 6076
#define Tileset1SGBPal1c1 8935
#define Tileset1SGBPal1c2 6596
#define Tileset1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Tileset1SGBPal2c0 6076
#define Tileset1SGBPal2c1 8935
#define Tileset1SGBPal2c2 6596
#define Tileset1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Tileset1SGBPal3c0 6076
#define Tileset1SGBPal3c1 8935
#define Tileset1SGBPal3c2 6596
#define Tileset1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Tileset1CGBPal0c0 26425
#define Tileset1CGBPal0c1 8935
#define Tileset1CGBPal0c2 6596
#define Tileset1CGBPal0c3 0

/* Gameboy Color palette 1 */
#define Tileset1CGBPal1c0 26425
#define Tileset1CGBPal1c1 32290
#define Tileset1CGBPal1c2 25600
#define Tileset1CGBPal1c3 0

/* Gameboy Color palette 2 */
#define Tileset1CGBPal2c0 26431
#define Tileset1CGBPal2c1 0
#define Tileset1CGBPal2c2 25
#define Tileset1CGBPal2c3 0

/* Gameboy Color palette 3 */
#define Tileset1CGBPal3c0 26431
#define Tileset1CGBPal3c1 30
#define Tileset1CGBPal3c2 25
#define Tileset1CGBPal3c3 0

/* Gameboy Color palette 4 */
#define Tileset1CGBPal4c0 6076
#define Tileset1CGBPal4c1 8935
#define Tileset1CGBPal4c2 6596
#define Tileset1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define Tileset1CGBPal5c0 6076
#define Tileset1CGBPal5c1 8935
#define Tileset1CGBPal5c2 6596
#define Tileset1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define Tileset1CGBPal6c0 6076
#define Tileset1CGBPal6c1 8935
#define Tileset1CGBPal6c2 6596
#define Tileset1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Tileset1CGBPal7c0 6076
#define Tileset1CGBPal7c1 8935
#define Tileset1CGBPal7c2 6596
#define Tileset1CGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char Tileset1CGB[];
/* Start of tile array. */
extern const unsigned char Tileset1[];

#endif

/* End of TILESET1.H */
