/*

 MAP05.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 40
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map05_h_INCLUDE
#define __map05_h_INCLUDE

#define Map05Width 20
#define Map05Height 40
#define Map05Bank 0

#define Map05 Map05PLN0
extern const unsigned char Map05PLN0[];
extern const unsigned char Map05PLN1[];

#endif

/* End of MAP05.H */
