/*

 MAP00.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 20
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map00_h_INCLUDE
#define __map00_h_INCLUDE

#define Map00Width 30
#define Map00Height 20
#define Map00Bank 0

#define Map00 Map00PLN0
extern const unsigned char Map00PLN0[];
extern const unsigned char Map00PLN1[];

#endif

/* End of MAP00.H */
