/*

 MAP09.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 24
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map09_h_INCLUDE
#define __map09_h_INCLUDE

#define Map09Width 40
#define Map09Height 24
#define Map09Bank 0

#define Map09 Map09PLN0
extern const unsigned char Map09PLN0[];
extern const unsigned char Map09PLN1[];

#endif

/* End of MAP09.H */
