/*

 MAP03.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 45 x 20
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map03_h_INCLUDE
#define __map03_h_INCLUDE

#define Map03Width 45
#define Map03Height 20
#define Map03Bank 0

#define Map03 Map03PLN0
extern const unsigned char Map03PLN0[];
extern const unsigned char Map03PLN1[];

#endif

/* End of MAP03.H */
