/*

 MAP10.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 38 x 23
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map10_h_INCLUDE
#define __map10_h_INCLUDE

#define Map10Width 38
#define Map10Height 23
#define Map10Bank 0

#define Map10 Map10PLN0
extern const unsigned char Map10PLN0[];
extern const unsigned char Map10PLN1[];

#endif

/* End of MAP10.H */
