/*

 MAP12.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 45 x 18
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map12_h_INCLUDE
#define __map12_h_INCLUDE

#define Map12Width 45
#define Map12Height 18
#define Map12Bank 0

#define Map12 Map12PLN0
extern const unsigned char Map12PLN0[];
extern const unsigned char Map12PLN1[];

#endif

/* End of MAP12.H */
