/*

 MAP11.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 38 x 24
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map11_h_INCLUDE
#define __map11_h_INCLUDE

#define Map11Width 38
#define Map11Height 24
#define Map11Bank 0

#define Map11 Map11PLN0
extern const unsigned char Map11PLN0[];
extern const unsigned char Map11PLN1[];

#endif

/* End of MAP11.H */
