/*

 MAP17.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 60
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map17_h_INCLUDE
#define __map17_h_INCLUDE

#define Map17Width 20
#define Map17Height 60
#define Map17Bank 0

#define Map17 Map17PLN0
extern const unsigned char Map17PLN0[];
extern const unsigned char Map17PLN1[];

#endif

/* End of MAP17.H */
