/*

 MAP13.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 45
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map13_h_INCLUDE
#define __map13_h_INCLUDE

#define Map13Width 25
#define Map13Height 45
#define Map13Bank 0

#define Map13 Map13PLN0
extern const unsigned char Map13PLN0[];
extern const unsigned char Map13PLN1[];

#endif

/* End of MAP13.H */
