/*

 0.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __0_h_INCLUDE
#define __0_h_INCLUDE

#define MapZeroWidth 32
#define MapZeroHeight 32
#define MapZeroBank 0

extern const unsigned char MapZero[];

#endif

/* End of 0.H */
