/*

 MAP07.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 20
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map07_h_INCLUDE
#define __map07_h_INCLUDE


const unsigned char* getMap07TilePlane() BANKED;
BANKREF_EXTERN(getMap07TilePlane)
const unsigned char* getMap07PalettePlane() BANKED;
BANKREF_EXTERN(getMap07PalettePlane)

extern const uint8_t getMap07Width() BANKED;
BANKREF_EXTERN(getMap07Width)
extern const uint8_t getMap07Height() BANKED;
BANKREF_EXTERN(getMap07Height)



extern const uint8_t Map07Width;
BANKREF_EXTERN(Map07Width)
extern const uint8_t Map07Height;
BANKREF_EXTERN(Map07Height)

extern const unsigned char Map07PLN0[];
BANKREF_EXTERN(Map07PLN0)
extern const unsigned char Map07PLN1[];
BANKREF_EXTERN(Map07PLN1)

#endif

/* End of MAP07.H */
