/*

 MAP04.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 45 x 20
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map04_h_INCLUDE
#define __map04_h_INCLUDE

#define Map04Width 45
#define Map04Height 20
#define Map04Bank 0

#define Map04 Map04PLN0
extern const unsigned char Map04PLN0[];
extern const unsigned char Map04PLN1[];

#endif

/* End of MAP04.H */
