/*

 MAP03.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 45 x 20
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map03_h_INCLUDE
#define __map03_h_INCLUDE


const unsigned char* getMap03TilePlane() BANKED;
BANKREF_EXTERN(getMap03TilePlane)
const unsigned char* getMap03PalettePlane() BANKED;
BANKREF_EXTERN(getMap03PalettePlane)

extern const uint8_t getMap03Width() BANKED;
BANKREF_EXTERN(getMap03Width)
extern const uint8_t getMap03Height() BANKED;
BANKREF_EXTERN(getMap03Height)



extern const uint8_t Map03Width;
BANKREF_EXTERN(Map03Width)
extern const uint8_t Map03Height;
BANKREF_EXTERN(Map03Height)

extern const unsigned char Map03PLN0[];
BANKREF_EXTERN(Map03PLN0)
extern const unsigned char Map03PLN1[];
BANKREF_EXTERN(Map03PLN1)
#endif

/* End of MAP03.H */
