/*

 MAP02.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 30
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map02_h_INCLUDE
#define __map02_h_INCLUDE



const unsigned char* getMap02TilePlane() BANKED;
BANKREF_EXTERN(getMap02TilePlane)
const unsigned char* getMap02PalettePlane() BANKED;
BANKREF_EXTERN(getMap02PalettePlane)

extern const uint8_t getMap02Width() BANKED;
BANKREF_EXTERN(getMap02Width)
extern const uint8_t getMap02Height() BANKED;
BANKREF_EXTERN(getMap02Height)



extern const uint8_t Map02Width;
BANKREF_EXTERN(Map02Width)
extern const uint8_t Map02Height;
BANKREF_EXTERN(Map02Height)

extern const unsigned char Map02PLN0[];
BANKREF_EXTERN(Map02PLN0)
extern const unsigned char Map02PLN1[];
BANKREF_EXTERN(Map02PLN1)
#endif

/* End of MAP02.H */
