/*

 MAP04.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 45 x 20
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map04_h_INCLUDE
#define __map04_h_INCLUDE


const unsigned char* getMap04TilePlane() BANKED;
BANKREF_EXTERN(getMap04TilePlane)
const unsigned char* getMap04PalettePlane() BANKED;
BANKREF_EXTERN(getMap04PalettePlane)

extern const uint8_t getMap04Width() BANKED;
BANKREF_EXTERN(getMap04Width)
extern const uint8_t getMap04Height() BANKED;
BANKREF_EXTERN(getMap04Height)



extern const uint8_t Map04Width;
BANKREF_EXTERN(Map04Width)
extern const uint8_t Map04Height;
BANKREF_EXTERN(Map04Height)

extern const unsigned char Map04PLN0[];
BANKREF_EXTERN(Map04PLN0)
extern const unsigned char Map04PLN1[];
BANKREF_EXTERN(Map04PLN1)

#endif

/* End of MAP04.H */
