/*

 MAP02.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 30
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map02_h_INCLUDE
#define __map02_h_INCLUDE

#define Map02Width 25
#define Map02Height 30
#define Map02Bank 0

#define Map02 Map02PLN0
extern const unsigned char Map02PLN0[];
extern const unsigned char Map02PLN1[];

#endif

/* End of MAP02.H */
