/*

 MAP06.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 40
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map06_h_INCLUDE
#define __map06_h_INCLUDE

#define Map06Width 40
#define Map06Height 40
#define Map06Bank 0

#define Map06 Map06PLN0
extern const unsigned char Map06PLN0[];
extern const unsigned char Map06PLN1[];

#endif

/* End of MAP06.H */
