/*

 MAP05.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 40
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map05_h_INCLUDE
#define __map05_h_INCLUDE

const unsigned char* getMap05TilePlane() BANKED;
BANKREF_EXTERN(getMap05TilePlane)
const unsigned char* getMap05PalettePlane() BANKED;
BANKREF_EXTERN(getMap05PalettePlane)

extern const uint8_t getMap05Width() BANKED;
BANKREF_EXTERN(getMap05Width)
extern const uint8_t getMap05Height() BANKED;
BANKREF_EXTERN(getMap05Height)



extern const uint8_t Map05Width;
BANKREF_EXTERN(Map05Width)
extern const uint8_t Map05Height;
BANKREF_EXTERN(Map05Height)

extern const unsigned char Map05PLN0[];
BANKREF_EXTERN(Map05PLN0)
extern const unsigned char Map05PLN1[];
BANKREF_EXTERN(Map05PLN1)

#endif

/* End of MAP05.H */
