/*

 MAP01.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 30
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map01_h_INCLUDE
#define __map01_h_INCLUDE



const unsigned char* getMap01TilePlane() BANKED;
BANKREF_EXTERN(getMap01TilePlane)
const unsigned char* getMap01PalettePlane() BANKED;
BANKREF_EXTERN(getMap01PalettePlane)

extern const uint8_t getMap01Width() BANKED;
BANKREF_EXTERN(getMap01Width)
extern const uint8_t getMap01Height() BANKED;
BANKREF_EXTERN(getMap01Height)



extern const uint8_t Map01Width;
BANKREF_EXTERN(Map01Width)
extern const uint8_t Map01Height;
BANKREF_EXTERN(Map01Height)

extern const unsigned char Map01PLN0[];
BANKREF_EXTERN(Map01PLN0)
extern const unsigned char Map01PLN1[];
BANKREF_EXTERN(Map01PLN1)
#endif

/* End of MAP01.H */
