/*

 MAP06.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 40
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map06_h_INCLUDE
#define __map06_h_INCLUDE


const unsigned char* getMap06TilePlane() BANKED;
BANKREF_EXTERN(getMap06TilePlane)
const unsigned char* getMap06PalettePlane() BANKED;
BANKREF_EXTERN(getMap06PalettePlane)

extern const uint8_t getMap06Width() BANKED;
BANKREF_EXTERN(getMap06Width)
extern const uint8_t getMap06Height() BANKED;
BANKREF_EXTERN(getMap06Height)



extern const uint8_t Map06Width;
BANKREF_EXTERN(Map06Width)
extern const uint8_t Map06Height;
BANKREF_EXTERN(Map06Height)

extern const unsigned char Map06PLN0[];
BANKREF_EXTERN(Map06PLN0)
extern const unsigned char Map06PLN1[];
BANKREF_EXTERN(Map06PLN1)

#endif

/* End of MAP06.H */
