/*

 MAP07.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 20
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map07_h_INCLUDE
#define __map07_h_INCLUDE

#define Map07Width 30
#define Map07Height 20
#define Map07Bank 0

#define Map07 Map07PLN0
extern const unsigned char Map07PLN0[];
extern const unsigned char Map07PLN1[];

#endif

/* End of MAP07.H */
