#include <gbdk/platform.h>

/*

 MAP08.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 40
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map08_h_INCLUDE
#define __map08_h_INCLUDE




#define Map08Width 20
#define Map08Height 40
#define Map08Bank 0

#define Map08 Map08PLN0
extern const unsigned char Map08PLN0[];
extern const unsigned char Map08PLN1[];

#endif

/* End of MAP08.H */
