
#include <gbdk/platform.h>

/*

 MAP09.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 24
   Tile set      : Z:\home\milan\Documents\gameboy\splat\src\maps\tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map09_h_INCLUDE
#define __map09_h_INCLUDE

// Reference for a banked function
void func_1() BANKED;
BANKREF_EXTERN(func_1)


const unsigned char* getMap09TilePlane() BANKED;
BANKREF_EXTERN(getMap09TilePlane)
const unsigned char* getMap09PalettePlane() BANKED;
BANKREF_EXTERN(getMap09PalettePlane)


extern const uint8_t Map09Width;
BANKREF_EXTERN(Map09Width)
extern const uint8_t Map09Height;
BANKREF_EXTERN(Map09Height)

extern const unsigned char Map09PLN0[];
BANKREF_EXTERN(Map09PLN0)
extern const unsigned char Map09PLN1[];
BANKREF_EXTERN(Map09PLN1)


#endif


/* End of MAP09.H */
