/*

 MAP14.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 30
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map14_h_INCLUDE
#define __map14_h_INCLUDE
const unsigned char* getMap14TilePlane() BANKED;
BANKREF_EXTERN(getMap14TilePlane)
const unsigned char* getMap14PalettePlane() BANKED;
BANKREF_EXTERN(getMap14PalettePlane)

extern const uint8_t getMap14Width() BANKED;
BANKREF_EXTERN(getMap14Width)
extern const uint8_t getMap14Height() BANKED;
BANKREF_EXTERN(getMap14Height)



extern const uint8_t Map14Width;
BANKREF_EXTERN(Map14Width)
extern const uint8_t Map14Height;
BANKREF_EXTERN(Map14Height)

extern const unsigned char Map14PLN0[];
BANKREF_EXTERN(Map14PLN0)
extern const unsigned char Map14PLN1[];
BANKREF_EXTERN(Map14PLN1)

#endif

/* End of MAP14.H */
