/*

 MAP10.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 35 x 20
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map10_h_INCLUDE
#define __map10_h_INCLUDE

const unsigned char* getMap10TilePlane() BANKED;
BANKREF_EXTERN(getMap10TilePlane)
const unsigned char* getMap10PalettePlane() BANKED;
BANKREF_EXTERN(getMap10PalettePlane)

extern const uint8_t getMap10Width() BANKED;
BANKREF_EXTERN(getMap10Width)
extern const uint8_t getMap10Height() BANKED;
BANKREF_EXTERN(getMap10Height)



extern const uint8_t Map10Width;
BANKREF_EXTERN(Map10Width)
extern const uint8_t Map10Height;
BANKREF_EXTERN(Map10Height)

extern const unsigned char Map10PLN0[];
BANKREF_EXTERN(Map10PLN0)
extern const unsigned char Map10PLN1[];
BANKREF_EXTERN(Map10PLN1)

#endif

/* End of MAP10.H */
