/*

 MAP11.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 38 x 23
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map11_h_INCLUDE
#define __map11_h_INCLUDE

const unsigned char* getMap11TilePlane() BANKED;
BANKREF_EXTERN(getMap11TilePlane)
const unsigned char* getMap11PalettePlane() BANKED;
BANKREF_EXTERN(getMap11PalettePlane)

extern const uint8_t getMap11Width() BANKED;
BANKREF_EXTERN(getMap11Width)
extern const uint8_t getMap11Height() BANKED;
BANKREF_EXTERN(getMap11Height)



extern const uint8_t Map11Width;
BANKREF_EXTERN(Map11Width)
extern const uint8_t Map11Height;
BANKREF_EXTERN(Map11Height)

extern const unsigned char Map11PLN0[];
BANKREF_EXTERN(Map11PLN0)
extern const unsigned char Map11PLN1[];
BANKREF_EXTERN(Map11PLN1)
#endif

/* End of MAP11.H */
