/*

 MAP12.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 45 x 18
   Tile set      : tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map12_h_INCLUDE
#define __map12_h_INCLUDE

const unsigned char* getMap12TilePlane() BANKED;
BANKREF_EXTERN(getMap12TilePlane)
const unsigned char* getMap12PalettePlane() BANKED;
BANKREF_EXTERN(getMap12PalettePlane)

extern const uint8_t getMap12Width() BANKED;
BANKREF_EXTERN(getMap12Width)
extern const uint8_t getMap12Height() BANKED;
BANKREF_EXTERN(getMap12Height)



extern const uint8_t Map12Width;
BANKREF_EXTERN(Map12Width)
extern const uint8_t Map12Height;
BANKREF_EXTERN(Map12Height)

extern const unsigned char Map12PLN0[];
BANKREF_EXTERN(Map12PLN0)
extern const unsigned char Map12PLN1[];
BANKREF_EXTERN(Map12PLN1)

#endif

/* End of MAP12.H */
