/*

 BLEED.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __bleed_h_INCLUDE
#define __bleed_h_INCLUDE

/* Bank of tiles. */
#define BleedTilesBank 0

/* Super Gameboy palette 0 */
#define BleedTilesSGBPal0c0 6076
#define BleedTilesSGBPal0c1 8935
#define BleedTilesSGBPal0c2 6596
#define BleedTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BleedTilesSGBPal1c0 6076
#define BleedTilesSGBPal1c1 8935
#define BleedTilesSGBPal1c2 6596
#define BleedTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BleedTilesSGBPal2c0 6076
#define BleedTilesSGBPal2c1 8935
#define BleedTilesSGBPal2c2 6596
#define BleedTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BleedTilesSGBPal3c0 6076
#define BleedTilesSGBPal3c1 8935
#define BleedTilesSGBPal3c2 6596
#define BleedTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BleedTilesCGBPal0c0 32767
#define BleedTilesCGBPal0c1 992
#define BleedTilesCGBPal0c2 744
#define BleedTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define BleedTilesCGBPal1c0 6076
#define BleedTilesCGBPal1c1 8935
#define BleedTilesCGBPal1c2 6596
#define BleedTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define BleedTilesCGBPal2c0 6076
#define BleedTilesCGBPal2c1 8935
#define BleedTilesCGBPal2c2 6596
#define BleedTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BleedTilesCGBPal3c0 6076
#define BleedTilesCGBPal3c1 8935
#define BleedTilesCGBPal3c2 6596
#define BleedTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BleedTilesCGBPal4c0 6076
#define BleedTilesCGBPal4c1 8935
#define BleedTilesCGBPal4c2 6596
#define BleedTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BleedTilesCGBPal5c0 6076
#define BleedTilesCGBPal5c1 8935
#define BleedTilesCGBPal5c2 6596
#define BleedTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BleedTilesCGBPal6c0 6076
#define BleedTilesCGBPal6c1 8935
#define BleedTilesCGBPal6c2 6596
#define BleedTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BleedTilesCGBPal7c0 6076
#define BleedTilesCGBPal7c1 8935
#define BleedTilesCGBPal7c2 6596
#define BleedTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char BleedTilesCGB[];
/* Start of tile array. */
extern const unsigned char BleedTiles[];

#endif

/* End of BLEED.H */
