/*

 PLAYERTILES1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playertiles1_h_INCLUDE
#define __playertiles1_h_INCLUDE

/* Bank of tiles. */
#define PlayerTiles1Bank 0

/* Super Gameboy palette 0 */
#define PlayerTiles1SGBPal0c0 6076
#define PlayerTiles1SGBPal0c1 8935
#define PlayerTiles1SGBPal0c2 6596
#define PlayerTiles1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerTiles1SGBPal1c0 6076
#define PlayerTiles1SGBPal1c1 8935
#define PlayerTiles1SGBPal1c2 6596
#define PlayerTiles1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerTiles1SGBPal2c0 6076
#define PlayerTiles1SGBPal2c1 8935
#define PlayerTiles1SGBPal2c2 6596
#define PlayerTiles1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerTiles1SGBPal3c0 6076
#define PlayerTiles1SGBPal3c1 8935
#define PlayerTiles1SGBPal3c2 6596
#define PlayerTiles1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerTiles1CGBPal0c0 32767
#define PlayerTiles1CGBPal0c1 744
#define PlayerTiles1CGBPal0c2 6117
#define PlayerTiles1CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define PlayerTiles1CGBPal1c0 6076
#define PlayerTiles1CGBPal1c1 8935
#define PlayerTiles1CGBPal1c2 6596
#define PlayerTiles1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PlayerTiles1CGBPal2c0 6076
#define PlayerTiles1CGBPal2c1 8935
#define PlayerTiles1CGBPal2c2 6596
#define PlayerTiles1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PlayerTiles1CGBPal3c0 6076
#define PlayerTiles1CGBPal3c1 8935
#define PlayerTiles1CGBPal3c2 6596
#define PlayerTiles1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerTiles1CGBPal4c0 6076
#define PlayerTiles1CGBPal4c1 8935
#define PlayerTiles1CGBPal4c2 6596
#define PlayerTiles1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerTiles1CGBPal5c0 6076
#define PlayerTiles1CGBPal5c1 8935
#define PlayerTiles1CGBPal5c2 6596
#define PlayerTiles1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerTiles1CGBPal6c0 6076
#define PlayerTiles1CGBPal6c1 8935
#define PlayerTiles1CGBPal6c2 6596
#define PlayerTiles1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerTiles1CGBPal7c0 6076
#define PlayerTiles1CGBPal7c1 8935
#define PlayerTiles1CGBPal7c2 6596
#define PlayerTiles1CGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char PlayerTiles1CGB[];
/* Start of tile array. */
extern const unsigned char PlayerTiles1[];

#endif

/* End of PLAYERTILES1.H */
