/*

 PLAYERTILES7.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playertiles7_h_INCLUDE
#define __playertiles7_h_INCLUDE

/* Bank of tiles. */
#define PlayerTiles7Bank 0

/* Super Gameboy palette 0 */
#define PlayerTiles7SGBPal0c0 6076
#define PlayerTiles7SGBPal0c1 8935
#define PlayerTiles7SGBPal0c2 6596
#define PlayerTiles7SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerTiles7SGBPal1c0 6076
#define PlayerTiles7SGBPal1c1 8935
#define PlayerTiles7SGBPal1c2 6596
#define PlayerTiles7SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerTiles7SGBPal2c0 6076
#define PlayerTiles7SGBPal2c1 8935
#define PlayerTiles7SGBPal2c2 6596
#define PlayerTiles7SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerTiles7SGBPal3c0 6076
#define PlayerTiles7SGBPal3c1 8935
#define PlayerTiles7SGBPal3c2 6596
#define PlayerTiles7SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerTiles7CGBPal0c0 32767
#define PlayerTiles7CGBPal0c1 744
#define PlayerTiles7CGBPal0c2 6117
#define PlayerTiles7CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define PlayerTiles7CGBPal1c0 6076
#define PlayerTiles7CGBPal1c1 8935
#define PlayerTiles7CGBPal1c2 6596
#define PlayerTiles7CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PlayerTiles7CGBPal2c0 6076
#define PlayerTiles7CGBPal2c1 8935
#define PlayerTiles7CGBPal2c2 6596
#define PlayerTiles7CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PlayerTiles7CGBPal3c0 6076
#define PlayerTiles7CGBPal3c1 8935
#define PlayerTiles7CGBPal3c2 6596
#define PlayerTiles7CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerTiles7CGBPal4c0 6076
#define PlayerTiles7CGBPal4c1 8935
#define PlayerTiles7CGBPal4c2 6596
#define PlayerTiles7CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerTiles7CGBPal5c0 6076
#define PlayerTiles7CGBPal5c1 8935
#define PlayerTiles7CGBPal5c2 6596
#define PlayerTiles7CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerTiles7CGBPal6c0 6076
#define PlayerTiles7CGBPal6c1 8935
#define PlayerTiles7CGBPal6c2 6596
#define PlayerTiles7CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerTiles7CGBPal7c0 6076
#define PlayerTiles7CGBPal7c1 8935
#define PlayerTiles7CGBPal7c2 6596
#define PlayerTiles7CGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char PlayerTiles7CGB[];
/* Start of tile array. */
extern const unsigned char PlayerTiles7[];

#endif

/* End of PLAYERTILES7.H */
