/*

 PLAYERTILES2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playertiles2_h_INCLUDE
#define __playertiles2_h_INCLUDE

/* Bank of tiles. */
#define PlayerTiles2Bank 0

/* Super Gameboy palette 0 */
#define PlayerTiles2SGBPal0c0 6076
#define PlayerTiles2SGBPal0c1 8935
#define PlayerTiles2SGBPal0c2 6596
#define PlayerTiles2SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerTiles2SGBPal1c0 6076
#define PlayerTiles2SGBPal1c1 8935
#define PlayerTiles2SGBPal1c2 6596
#define PlayerTiles2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerTiles2SGBPal2c0 6076
#define PlayerTiles2SGBPal2c1 8935
#define PlayerTiles2SGBPal2c2 6596
#define PlayerTiles2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerTiles2SGBPal3c0 6076
#define PlayerTiles2SGBPal3c1 8935
#define PlayerTiles2SGBPal3c2 6596
#define PlayerTiles2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerTiles2CGBPal0c0 32767
#define PlayerTiles2CGBPal0c1 744
#define PlayerTiles2CGBPal0c2 6117
#define PlayerTiles2CGBPal0c3 5344

/* Gameboy Color palette 1 */
#define PlayerTiles2CGBPal1c0 6076
#define PlayerTiles2CGBPal1c1 8935
#define PlayerTiles2CGBPal1c2 6596
#define PlayerTiles2CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PlayerTiles2CGBPal2c0 6076
#define PlayerTiles2CGBPal2c1 8935
#define PlayerTiles2CGBPal2c2 6596
#define PlayerTiles2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PlayerTiles2CGBPal3c0 6076
#define PlayerTiles2CGBPal3c1 8935
#define PlayerTiles2CGBPal3c2 6596
#define PlayerTiles2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerTiles2CGBPal4c0 6076
#define PlayerTiles2CGBPal4c1 8935
#define PlayerTiles2CGBPal4c2 6596
#define PlayerTiles2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerTiles2CGBPal5c0 6076
#define PlayerTiles2CGBPal5c1 8935
#define PlayerTiles2CGBPal5c2 6596
#define PlayerTiles2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerTiles2CGBPal6c0 6076
#define PlayerTiles2CGBPal6c1 8935
#define PlayerTiles2CGBPal6c2 6596
#define PlayerTiles2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerTiles2CGBPal7c0 6076
#define PlayerTiles2CGBPal7c1 8935
#define PlayerTiles2CGBPal7c2 6596
#define PlayerTiles2CGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char PlayerTiles2CGB[];
/* Start of tile array. */
extern const unsigned char PlayerTiles2[];

#endif

/* End of PLAYERTILES2.H */
