/*

 PLAYERTILES5.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playertiles5_h_INCLUDE
#define __playertiles5_h_INCLUDE

/* Bank of tiles. */
#define PlayerTiles5Bank 0

/* CGBpalette entries. */
extern const unsigned char PlayerTiles5CGB[];
/* Start of tile array. */
extern const unsigned char PlayerTiles5[];

#endif

/* End of PLAYERTILES5.H */
